name : credit-fraud-detection
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - catboost
  - lightgbm
  - requests
  - joblib
  - optuna
  - kagglehub
  - ipykernel

