name : credit-fraud-detection
channels:
  - conda-forge
dependencies:
  - python==3.10
  - numpy==1.23.5
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - catboost==1.2.2
  - lightgbm
  - requests
  - joblib
  - optuna
  - kagglehub
  - ipykernel

