name : credit-fraud-detection
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - catboost
  - lightgbm
  - requests
  - pip
  - joblib
  - optuna
  - kagglehub=0.3.12
  - ipykernel

